### PR TITLE
Support Terraform 1.x

### PR DESCRIPTION
**Pull request by Integralist**
I updated my terraform version from 0.15 to 1.1.4 and noticed an error when running the tests...

```
error: unsupported state format version: expected ["0.1" "0.2"], got "1.0"
```

The fix that was suggested from the terratest project was to bump the `terraform-json` dependency (and worked).

### CODE REVIEW

**Comment by Integralist** [comment]
I ran the tests using both 0.x and 1.x terraform version and they both now pass.

**Review by kailan — APPROVED** [review]

**Comment by smaeda-ks** [comment]
@Integralist Was this really required? I think we fixed this before:https://github.com/fastly/terraform-provider-fastly/pull/474
and I had no issues with v1 binary since then. I might think this was your local env specific problem.

**Comment by smaeda-ks** [comment]
Ah, never mind. I see it now:
https://github.com/hashicorp/terraform-json/commit/1b370c6345872777de33f05853a25e94cebe1f3d

**Comment by smaeda-ks** [comment]
Looking at the changelogs, it probably makes more sense (and safe) to bump the SDK version rather than adding the indirect reference.
https://github.com/hashicorp/terraform-plugin-sdk/blob/main/CHANGELOG.md

```
	github.com/hashicorp/terraform-plugin-sdk/v2 v2.7.1
```

to 

```
	github.com/hashicorp/terraform-plugin-sdk/v2 v2.10.1
```

which should also fix this.

ref. https://github.com/hashicorp/terraform-plugin-sdk/commit/a928a7b22790d6946de295c1e5cd884be2cf1fc7

**Comment by Integralist** [comment]
Cool. I'll look at bumping the sdk version 👍🏻

**Pull request merged**
