### PR TITLE
Custom TLS Resources

### PR DESCRIPTION
**Pull request by joel-g**
This is a draft WIP. 

I am hoping to get some feedback. I will also need to add data sources for TLSConfiguration, CustomTLSCertificate and tests for everything. This PR is dependent on https://github.com/fastly/go-fastly/pull/225

cc: @Integralist @phamann

### CODE REVIEW

**Comment by Integralist** [comment]
Thanks @joel-g 

Once I've had a chance to review your latest comments on https://github.com/fastly/go-fastly/pull/225 (which I'll do today) and I'm ready to approve/merge your PR, then I'll be able to circle back round to giving this PR a review. 

Please let me know when it's no longer WIP and ready for a full review.

**Comment by joel-g** [comment]
@Integralist This is ready for review 😀

You'll see I am hoping for some guidance on TLSActivation testing

**Comment by joel-g** [comment]
This is ready for review. Because TLS Configurations cannot be created via API an env variable FASTLY_TESTING_TLS_CONFIGURATION_ID must be set equal to a valid TLS Configuration ID on the testing account.

**Comment by joel-g** [comment]
@Integralist this is ready for review

**Comment by Integralist** [comment]
As discussed in Slack with Joel, we're going to close this PR as we have an internal team about to start work on implementing all missing TLS features within Terraform and so we would like them to handle the implementation for consistency. 

**But just to reiterate what we mentioned in Slack**:  
We really appreciate the time taken to implement this feature and we're glad in doing so it helped you to unblock part of your work stream ❤️

**Pull request closed without merging**
