### PR TITLE
use `TypeList` schema for `gzip` nested block attributes

### PR DESCRIPTION
**Pull request by smaeda-ks**
resuming the previous work: https://github.com/fastly/terraform-provider-fastly/pull/433

### CODE REVIEW

**Comment by smaeda-ks** [comment]
Performed full tests. Should be good to merge (in v1). @Integralist

**Review by Integralist — APPROVED** [review]
LGTM.

**Comment by Hiieu** [comment]
The changes in this PR have been merged into the v1 branch in the OC fork: https://github.com/opencredo/terraform-provider-fastly/pull/114

**Comment by Integralist** [comment]
Closing as per the above comment. This is because we're consolidating all changes destined for `v1.0.0` of the Fastly Terraform provider into the [opencredo/v1](https://github.com/opencredo/terraform-provider-fastly/tree/v1) branch and will then soon be merged into the Fastly [v1](https://github.com/fastly/terraform-provider-fastly/tree/v1) branch, which will at some near point in the future make its way into `main` for a new release to be cut.

**Pull request closed without merging**
