### PR TITLE
Add google account name to all gcp logging endpoints

### PR DESCRIPTION
**Pull request by grantstephens**
Blocked- waiting for the new version of go-fastly

### CODE REVIEW

**Comment by Integralist** [comment]
@grantstephens The v7 go-fastly release out and I'm still working on integrating it into the Terraform provider (lots of breaking changes that need fixing). So just wanted to let you know that I've not forgotten about this 🙂

**Comment by domfee** [comment]
@Integralist thanks for the update. We are committed to having the TF update out by 30th November. Is that realistic from your side?

**Comment by Integralist** [comment]
We have an internal API change that is currently blocking the go-fastly integration as it's causing one of the Terraform tests to fail. The relevant team is working on this currently so hopefully I'll be unblocked shortly and can wrap up the integration today or tomorrow (PR review permitting).

**Comment by Integralist** [comment]
I've run the tests locally and I'm finding errors like this:

```
➜  make testacc TESTARGS='-run=TestAccFastlyServiceVCL_googlepubsublogging'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccFastlyServiceVCL_googlepubsublogging -parallel=4 -timeout 360m -ldflags="-X=github.com/fastly/terraform-provider-fastly/version.ProviderVersion=acc"
?       github.com/fastly/terraform-provider-fastly     [no test files]
=== RUN   TestAccFastlyServiceVCL_googlepubsublogging_basic
=== PAUSE TestAccFastlyServiceVCL_googlepubsublogging_basic
=== RUN   TestAccFastlyServiceVCL_googlepubsublogging_basic_compute
=== PAUSE TestAccFastlyServiceVCL_googlepubsublogging_basic_compute
=== CONT  TestAccFastlyServiceVCL_googlepubsublogging_basic
=== CONT  TestAccFastlyServiceVCL_googlepubsublogging_basic_compute
    block_fastly_service_logging_googlepubsub_test.go:251: Step 1/1 error: Error running apply: exit status 1

        Error: 400 - Bad Request:

            Title:  Bad request
            Detail: Invalid account_name ''

          with fastly_service_compute.foo,
          on terraform_plugin_test.tf line 2, in resource "fastly_service_compute" "foo":
           2: resource "fastly_service_compute" "foo" {

=== CONT  TestAccFastlyServiceVCL_googlepubsublogging_basic
    block_fastly_service_logging_googlepubsub_test.go:203: Step 1/2 error: Error running apply: exit status 1

        Error: 400 - Bad Request:

            Title:  Bad request
            Detail: Invalid account_name ''

          with fastly_service_vcl.foo,
          on terraform_plugin_test.tf line 2, in resource "fastly_service_vcl" "foo":
           2: resource "fastly_service_vcl" "foo" {

--- FAIL: TestAccFastlyServiceVCL_googlepubsublogging_basic_compute (4.58s)
--- FAIL: TestAccFastlyServiceVCL_googlepubsublogging_basic (5.56s)
FAIL
FAIL    github.com/fastly/terraform-provider-fastly/fastly      6.100s
?       github.com/fastly/terraform-provider-fastly/fastly/hashcode     [no test files]
?       github.com/fastly/terraform-provider-fastly/version     [no test files]
FAIL
make: *** [testacc] Error 1
```

I think you'll need to do something like [this](https://github.com/fastly/terraform-provider-fastly/blob/c5ec12fc7922577d3c1cbd4153c3de903b631310/fastly/block_fastly_service_logging_googlepubsub.go#L254-L273)

Where you remove `AccountName` from the `&gofastly.CreatePubsubInput` and add an extra `if` conditional that checks something like:

```go
if v, ok := resource["account_name"].(string) && (ok && v != "") {
  opts.AccountName = gofastly.String(v)
}
```

And just apply a similar change for the other affected files.

**Pull request merged**
