### PR TITLE
Support message_type attribute for s3logging

### PR DESCRIPTION
**Pull request by bart613**
It'd be really useful to be able to specify `message_type` attribute on `s3logging` configuration. This would allow us to eg. log to s3 in JSON format (if we set `message_type` to `blank` we can then build JSON structure using `format`).

Default value for `message_type` will be set to `classic` which will not change the default behaviour of Fastly - as per [[1]](https://docs.fastly.com/api/logging) - if not specified, `message_type` defaults to `classic`.

PR includes also update for vendor library `go-fastly` as it includes support for `message_type` in s3logging.

[[1] - https://docs.fastly.com/api/logging](https://docs.fastly.com/api/logging)

### CODE REVIEW

**Comment by stack72** [comment]
Hi @bart613 

Thanks for the work here - please can you add the following to help us:

1. Documentation. We need to make sure that users know this exists
2. An acceptance test to show how setting this then changing it will persist the change to state

Thanks 

Paul

**Comment by bart613** [comment]
Hey @stack72 - thank you for follow-up and apologies - these should be included in the first place.

Just added acceptance test and documentation - please have a look whether it's good enough.

**Comment by stack72** [comment]
Hi @bart613 

Thanks for making the changes. Unfortunately, the test that you modified now fails:

```
=== RUN   TestAccFastlyServiceV1_s3logging_s3_env
--- FAIL: TestAccFastlyServiceV1_s3logging_s3_env (22.42s)
	testing.go:428: Step 0 error: Check failed: Check 2/4 error: Bad match S3 logging match, expected (&fastly.S3{ServiceID:"7ZHCuqYlK4ZdPyOKk0q6uG", Version:1, Name:"somebucketlog", BucketName:"fastlytestlogging", Domain:"s3-us-west-2.amazonaws.com", AccessKey:"someEnv", SecretKey:"someEnv", Path:"", Period:0xe10, GzipLevel:0x0, Format:"%h %l %u %t %r %>s", FormatVersion:0x1, ResponseCondition:"", MessageType:"", TimestampFormat:"%Y-%m-%dT%H:%M:%S.000", Redundancy:"", CreatedAt:(*time.Time)(nil), UpdatedAt:(*time.Time)(nil), DeletedAt:(*time.Time)(nil)}), got (&fastly.S3{ServiceID:"7ZHCuqYlK4ZdPyOKk0q6uG", Version:1, Name:"somebucketlog", BucketName:"fastlytestlogging", Domain:"s3-us-west-2.amazonaws.com", AccessKey:"someEnv", SecretKey:"someEnv", Path:"", Period:0xe10, GzipLevel:0x0, Format:"%h %l %u %t %r %>s", FormatVersion:0x1, ResponseCondition:"", MessageType:"classic", TimestampFormat:"%Y-%m-%dT%H:%M:%S.000", Redundancy:"", CreatedAt:(*time.Time)(nil), UpdatedAt:(*time.Time)(nil), DeletedAt:(*time.Time)(nil)})
=== RUN   TestAccFastlyServiceV1_s3logging_formatVersion
--- FAIL: TestAccFastlyServiceV1_s3logging_formatVersion (22.70s)
	testing.go:428: Step 0 error: Check failed: Check 2/4 error: Bad match S3 logging match, expected (&fastly.S3{ServiceID:"Bp8WX91UIsApJawUMQBza", Version:1, Name:"somebucketlog", BucketName:"fastlytestlogging", Domain:"s3-us-west-2.amazonaws.com", AccessKey:"somekey", SecretKey:"somesecret", Path:"", Period:0xe10, GzipLevel:0x0, Format:"%a %l %u %t %m %U%q %H %>s %b %T", FormatVersion:0x2, ResponseCondition:"", MessageType:"", TimestampFormat:"%Y-%m-%dT%H:%M:%S.000", Redundancy:"", CreatedAt:(*time.Time)(nil), UpdatedAt:(*time.Time)(nil), DeletedAt:(*time.Time)(nil)}), got (&fastly.S3{ServiceID:"Bp8WX91UIsApJawUMQBza", Version:1, Name:"somebucketlog", BucketName:"fastlytestlogging", Domain:"s3-us-west-2.amazonaws.com", AccessKey:"somekey", SecretKey:"somesecret", Path:"", Period:0xe10, GzipLevel:0x0, Format:"%a %l %u %t %m %U%q %H %>s %b %T", FormatVersion:0x2, ResponseCondition:"", MessageType:"classic", TimestampFormat:"%Y-%m-%dT%H:%M:%S.000", Redundancy:"", CreatedAt:(*time.Time)(nil), UpdatedAt:(*time.Time)(nil), DeletedAt:(*time.Time)(nil)})
```

Please can you have a look at it?

Thanks

Paul

**Comment by bart613** [comment]
@stack72 argh - should be fixed now; sorry!

**Comment by stack72** [comment]
Hi @bart613 

Thanks so much for working with me to get this all ready - :) This now is looking great and is ready to merge

```
% make testacc TEST=./fastly
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./fastly -v  -timeout 120m
=== RUN   TestAccFastlyIPRanges
--- PASS: TestAccFastlyIPRanges (1.71s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccFastlyServiceV1CacheSetting_basic
--- PASS: TestAccFastlyServiceV1CacheSetting_basic (62.08s)
=== RUN   TestAccFastlyServiceV1_conditional_basic
--- PASS: TestAccFastlyServiceV1_conditional_basic (26.74s)
=== RUN   TestResourceFastlyFlattenGCS
--- PASS: TestResourceFastlyFlattenGCS (0.00s)
=== RUN   TestAccFastlyServiceV1_gcslogging
--- PASS: TestAccFastlyServiceV1_gcslogging (35.15s)
=== RUN   TestFastlyServiceV1_FlattenGzips
--- PASS: TestFastlyServiceV1_FlattenGzips (0.00s)
=== RUN   TestAccFastlyServiceV1_gzips_basic
--- PASS: TestAccFastlyServiceV1_gzips_basic (64.64s)
=== RUN   TestFastlyServiceV1_BuildHeaders
--- PASS: TestFastlyServiceV1_BuildHeaders (0.00s)
=== RUN   TestAccFastlyServiceV1_headers_basic
--- PASS: TestAccFastlyServiceV1_headers_basic (65.76s)
=== RUN   TestAccFastlyServiceV1_healthcheck_basic
--- PASS: TestAccFastlyServiceV1_healthcheck_basic (61.51s)
=== RUN   TestAccFastlyServiceV1_papertrail_basic
--- PASS: TestAccFastlyServiceV1_papertrail_basic (58.99s)
=== RUN   TestAccFastlyServiceV1RequestSetting_basic
--- PASS: TestAccFastlyServiceV1RequestSetting_basic (26.75s)
=== RUN   TestAccFastlyServiceV1_response_object_basic
--- PASS: TestAccFastlyServiceV1_response_object_basic (63.11s)
=== RUN   TestAccFastlyServiceV1_s3logging_basic
--- PASS: TestAccFastlyServiceV1_s3logging_basic (60.08s)
=== RUN   TestAccFastlyServiceV1_s3logging_s3_env
--- PASS: TestAccFastlyServiceV1_s3logging_s3_env (29.91s)
=== RUN   TestAccFastlyServiceV1_s3logging_formatVersion
--- PASS: TestAccFastlyServiceV1_s3logging_formatVersion (28.88s)
=== RUN   TestResourceFastlyFlattenSumologic
--- PASS: TestResourceFastlyFlattenSumologic (0.00s)
=== RUN   TestAccFastlyServiceV1_sumologic
--- PASS: TestAccFastlyServiceV1_sumologic (30.28s)
=== RUN   TestResourceFastlyFlattenDomains
--- PASS: TestResourceFastlyFlattenDomains (0.00s)
=== RUN   TestResourceFastlyFlattenBackend
--- PASS: TestResourceFastlyFlattenBackend (0.00s)
=== RUN   TestAccFastlyServiceV1_updateDomain
--- PASS: TestAccFastlyServiceV1_updateDomain (59.55s)
=== RUN   TestAccFastlyServiceV1_updateBackend
--- PASS: TestAccFastlyServiceV1_updateBackend (60.25s)
=== RUN   TestAccFastlyServiceV1_basic
--- PASS: TestAccFastlyServiceV1_basic (26.09s)
=== RUN   TestAccFastlyServiceV1_disappears
--- PASS: TestAccFastlyServiceV1_disappears (14.78s)
=== RUN   TestAccFastlyServiceV1_defaultTTL
--- PASS: TestAccFastlyServiceV1_defaultTTL (91.38s)
=== RUN   TestAccFastlyServiceV1_VCL_basic
--- PASS: TestAccFastlyServiceV1_VCL_basic (57.51s)
=== RUN   TestValidateLoggingFormatVersion
--- PASS: TestValidateLoggingFormatVersion (0.00s)
=== RUN   TestValidateLoggingMessageType
--- PASS: TestValidateLoggingMessageType (0.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-fastly/fastly	925.162s
```

Paul

**Comment by bart613** [comment]
Thanks @stack72 - appreciate all the help! :-)

**Pull request merged**
