### PR TITLE
Support hash Snippet Types

### PR DESCRIPTION
**Pull request by soldiermoth**
The type `"hash"` appears to be missing from the list of valid Snippet Types.
Fastly's documentation for allowable types https://docs.fastly.com/api/config#api-section-snippet

### CODE REVIEW

**Comment by soldiermoth** [comment]
It looks like the Travis build passed but is still showing Pending in GitHub: https://travis-ci.org/terraform-providers/terraform-provider-fastly/builds/654597126?utm_medium=notification&utm_source=github_status

**Comment by soldiermoth** [comment]
Is there a process for getting this looked at?

**Review by philippschulte — CHANGES_REQUESTED** [review]
@soldiermoth thanks for your contribution and sorry for the delay in getting back to you! Every validator is covered by unit tests. Therefore, please add the new type to `TestValidateSnippetType` located at `fastly/validators_test.go`. Thank you

**Comment by soldiermoth** [comment]
@philippschulte No worries, thanks for getting back to me. Happy to add it to those tests, should be good to go now.

**Review by philippschulte — APPROVED** [review]
@soldiermoth thanks for updating the test. I also wanted to confirm @phamann is happy with this before merging.

**Review by phamann — APPROVED** [review]
Apologies for the delayed response, yes I'm happy :+1:

Thank you for your contribution @soldiermoth

**Pull request merged**
