### PR TITLE
Remove mTLS from state that returns 404

### PR DESCRIPTION
**Pull request by hvtonev**
When TLS Mutual Authentication is removed outside of terraform the following error occurs.

```terraform
╷
│ Error: 404 - Not Found:
│ 
│     Title:  Not found
│     Detail: The mutual_authentication you requested was not found
│ 
│ 
╵
```

Expected is to be removed from the state instead, similar to TLS Subscription

### CODE REVIEW

**Review by Integralist — COMMENTED** [review]
👋🏻 Thanks for opening this PR!

I don't think the `if` condition works as expected. Take a look at [this reduced test case](https://play.golang.com/p/Nfr8r2fnc06) and let me know your thoughts.

Thanks.

**Comment by hvtonev** [comment]
> 👋🏻 Thanks for opening this PR!
> 
> I don't think the `if` condition works as expected. Take a look at [this reduced test case](https://play.golang.com/p/Nfr8r2fnc06) and let me know your thoughts.
> 
> Thanks.

Agree. If the type assertion fails `err` will become `nil`. Thanks for pointing this out

**Review by Integralist — APPROVED** [review]
Thanks for updating the PR @hvtonev 

This is now approved and I'll look to get it merged shortly.

**Comment by Integralist** [comment]
@hvtonev would it be possible to merge the latest `main` into your fork's PR branch and push back up as I'm trying to validate a new CI workflow that validates the exposed interface but looks like this PR is stuck seeing the old CI job. Thanks!

**Comment by hvtonev** [comment]
@Integralist Done

**Pull request merged**
