### PR TITLE
feat(tls_activation): support mutual_authentication_id in domain activation at creation

### PR DESCRIPTION
**Pull request by landrew57**
- add test case for activation with mTLS

This fails on `main` because the `mutual_authentication_id` is not set on an activation when it is created
but it is set in the terraform state.

- `mutual_authentication_id` cannot be set when activation is created

`Update` the domain activation once it has been created to add the `mutual_authentication_id` to the configuration.

Related to fastly/terraform-provider-fastly/issues/870 and https://github.com/fastly/terraform-provider-fastly/issues/873

### CODE REVIEW

**Comment by kpfleming** [comment]
This looks good so far, I'll pull it down to my machine and run the acceptance tests.

**Review by kpfleming — APPROVED** [review]
Acceptance test passes.

**Comment by kpfleming** [comment]
Thank you for the contribution!

**Comment by landrew57** [comment]
Hey @kpfleming do you know when a new release will be available with this change?

**Comment by kpfleming** [comment]
We haven't scheduled one yet, but if possible I'll get one made early next week.

**Comment by kpfleming** [comment]
Version 5.12.0 was just released.

**Pull request merged**
