### PR TITLE
Add support for New Relic OTLP endpoint

### PR DESCRIPTION
**Pull request by mdenomy**
Adds support for the [New Relic OTLP](https://docs.fastly.com/en/guides/log-streaming-newrelic-otlp) logging endpoint

### CODE REVIEW

**Comment by Integralist** [comment]
👋🏻 Can you run `make generate-docs` locally, and commit the changes and push them up again.

I've given the @fastly/systems team (of which you are a member) WRITE access, which should mean the `validate-interface` CI job will run with access to the GitHub Secret token (your previous push failed that CI job because you were  not recognised as a contributor and so you don't get access to the GitHub secrets).

**Comment by Integralist** [comment]
@mdenomy My apologies but would it be possible (now I've given your GitHub team WRITE access) to close this PR and re-open it directly on this repo as a contributor with direct WRITE access (i.e. rather than opening a pull request via your fork of this repo)? 

The reason being is that the `validate-interface` CI job (which is an important job as it helps identify potential breaking changes in the Terraform interface) needs access to an environment secret to run, but GitHub won't expose the secret when the workflow is run on a PR that's from a _fork_ of the repo.

Apologies again, I appreciate it's a bit of a pain to have to ask this 😞

**Comment by mdenomy** [comment]
@Integralist not a problem at all, thanks for the help.

**Comment by mdenomy** [comment]
Closing to open a new PR directly on this repo to be able to run `validate-interface`

**Pull request closed without merging**
