### PR TITLE
Remove go-version

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by Integralist** [comment]
Hi @chenrui333 we were looking to deprecate this file (as we do not use it internally, as we already define the relevant supported go version within the CI configuration). 

Can you let me know what its/your use case is.

Thanks!

**Comment by chenrui333** [comment]
No use case for me, just saw this file is out of sync.

**Comment by chenrui333** [comment]
Ideally, it would be nice to have such file in the repo though (kind of metadata), but yeah, it does require some sort of maintenance work (which I am happy to help with)

**Comment by Integralist** [comment]
We actually already have this information in the `go.mod` which is our preferred method of documenting it. Feel free to update your PR to remove the `.go-version` file, otherwise we'll go ahead and close this PR and handle the deletion ourselves. 

Thanks @chenrui333

**Comment by chenrui333** [comment]
Sounds good, let's remove it.

**Review by Integralist — APPROVED** [review]

**Pull request merged**
